server:
  port: 8180

spring:
  datasource:
    url: jdbc:mysql://incurance-policy.cfwpjgkmdv6h.us-east-1.rds.amazonaws.com/insurance
    username: admin
    password: 123admin
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  

