server:
  port: 8180

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerMicroservice
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: Mongo DB Example
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongo 
      repositories:
        enabled: true 

#logging:
#  level:
#    root: INFO      
#    com:
#      customer: TRACE      
  

